spring:
  datasource:
    password: Pass1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/users
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
minio:
  url: http://172.17.0.2:9000
  bucket: userserver
  access-key: minio
  secret-key: minio1234
  image-folder: profpic/
  video-folder: video/

file:
  upload:
    acceptableVideoExtensions: mp4,mov,avi,wmv
    acceptableImageExtensions: jpg,png,jpeg