spring:
  datasource:
    password: Pass1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/users
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
minio:
  folder: mtipic/
  url: https://play.min.io
  bucket: 00000qweqwe
  access-key: Q3AM3UQ867SPQQA43P2F
  secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

file:
  upload:
    acceptableExtensions: jpg,png,jpeg